### ISSUE TITLE
Refactor the `config`

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/dashboards#593]
Currently we name every field that we can filter by in the config but now that we offer more filter options it would be good to extend the config to make this more generic 
This is how our config currently looks like: https://github.com/GenSpectrum/dashboards/blob/main/backend/src/main/resources/application-dashboards-prod.yaml

I would propose moving to a more generic option, similar to the Loculus config:
```
dashboards:
  organisms:
    covid:
      lapis:
        url: "https://lapis.cov-spectrum.org/open/v2"
        fields:
          - lapisField: "hostNameScientific"
            label: "host"
            type: text
            initialSearchOption: true
          - lapisField: "originatingLab"
            label: "originating lab"
            type: text
            initialSearchOption: false
          - lapisField: "region"
            label: "Region"
            type: location
            initialSearchOption: true
          - lapisField: "country"
            label: "Country"
            type: location
            initialSearchOption: true
          - lapisField: "date"
            label: "Collection Date"
            type: date
            initialSearchOption: true
```
